### ISSUE TITLE
Selector callback for chosentree

### ISSUE THREAD

**Issue by TimFoerster** [travist/jquery.treeselect.js#13]
Is it possible to add a callback/listener for the chosentree?

For example:

```
$('.chosentree').chosentree({
   selected: function(obj, success) {
      console.log('node has been selected');
      console.log(obj);        
   }, 
   ...
});
```

```
Example can be found here: https://jsfiddle.net/vz1neoyw/1/
```

**Comment by travist** [comment]
Unfortunately this is overriding it... https://github.com/travist/jquery.treeselect.js/blob/master/src/jquery.chosentree.js#L260

What may work is to make a patch like this....

```
      // Store the current selected argument.
      var _selected = treeparams.selected;

      // Reset the selected callback.
      treeparams.selected = (function(chosentree) {

        // Keep track of the selected nodes.
        var selectedNodes = {};

        // The node callback.
        return function(node, direct) {

          // Call the stored selected callback.
          if (_selected) { _selected(node, direct); }
```

**Comment by glemmon** [comment]
I'm using a chosentree. Currently, when an item is selected via the checkbox, its children are auto-selected. I tried reversing this by setting "autoSelectChildren: false" on line 211 of jquery.treeselect.js, with no effect. What am I doing wrong?

Another option would be to disable selection of all but leaf nodes. Is this a possibility?
