### ISSUE TITLE
Tag 1.0.0?

### ISSUE THREAD

**Issue by RobLoach** [travist/jquery.treeselect.js#7]
http://semver.org

**Comment by travist** [comment]
I think version 1.0.0 is justified.  We have been using this in our production software for some time now.  Will push up an update soon simply tagging current SHA as version 1.0.0.

**Comment by travist** [comment]
p.s.  Are you at DrupalCon?  I am here if you would like help implementing this widget.

**Comment by RobLoach** [comment]
@travist Would love to help out! I'm unfortunately missing out at Drupalcon, however. Got something started over at http://github.com/robloach/jquerytreeselect . I'll be on #drupal tomorrow :+1: .

**Comment by travist** [comment]
This may help provide you a live example of AllPlayers.com using this.

http://www.allplayers.com/sites/all/libraries/allplayers.js/lib/group_finder/index.html

All of the code in this library is also provided open source @ https://github.com/AllPlayers/allplayers.js

You can watch the traffic of this, but it hits the https://www.allplayers.com/api/v1/rest/groups/a22af7fd-ff1a-11e2-9d8d-22000a929134/subgroups/tree.jsonp?depth=2 endpoint which is an example of how we use this library for our group finder.

Let me know if you need any help.

**Comment by travist** [comment]
Just added the tag 1.0.0 to current version.
