### ISSUE TITLE
Callback; loaded, results in undefined nodes

### ISSUE THREAD

**Issue by RobLoach** [travist/jquery.treeselect.js#8]
Uncaught ReferenceError: nodes is not defined 

```
            // If they wish to know when it is loaded.
            if (treeparams.loaded) {

              // Call our callback with all the nodes.
              treeparams.loaded(nodes);
            }
```

**Comment by travist** [comment]
This should now be fixed with the latest commit.  I am now passing the `node` object to the callback, which is an instance of `TreeNode`.  This includes the children if you wish to get access to all the children within that node.
