### ISSUE TITLE
Checkboxes not working properly in jQuery 1.11.1

### ISSUE THREAD

**Issue by vuhuy** [travist/jquery.treeselect.js#9]
The script is partially broken when using new versions of jQuery, at least for jQuery version 1.11.1. For DOM properties like checked, it is required to use prop instead of attr for setting the checkbox state. For example, when setting autoSelectChildren to true, the child nodes does not appear to be checked when selecting the parent node. Changing this.input.attr('checked', state) to this.input.prop('checked', state) fixes the problem for me.

**Comment by travist** [comment]
I just pushed up a fix for this, but did it a little bit different so that it works for all versions of jQuery.  Instead of setting the attribute with jQuery, I am now simply just referencing the `checked` parameter on the Input DOM element, like this.

```
// To check the checkbox.
this.input.eq(0)[0].checked = true;
```

Let me know if this works for you.
